import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Hero from '@/sections/Hero';
import Button from '@/components/Button';
import GridContainer from '@/components/Containers/GridContainer';
import Footer from '@/sections/Footer';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
	weight: ['400', '500', '700', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<Header />

				{children}
				<Footer />
			</body>
		</html>
	);
}
